# Generated by Django 4.0.2 on 2022-03-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_userlogin_delete_productdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='image',
            field=models.FileField(null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
