# Generated by Django 4.0.2 on 2022-03-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_title_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
