# Generated by Django 4.0.2 on 2022-03-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_title_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='curt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('itmes', models.ImageField(blank=True, null=True, upload_to='product/items')),
                ('price', models.IntegerField(null=True)),
            ],
        ),
    ]
