# Generated by Django 4.0.2 on 2022-03-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_curt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curt',
            name='itmes',
        ),
        migrations.AlterField(
            model_name='curt',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
