# Generated by Django 4.0.2 on 2022-03-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_curt_itmes_alter_curt_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='curt',
            name='itmes',
            field=models.ImageField(blank=True, null=True, upload_to='product/items'),
        ),
    ]
