# Generated by Django 4.0.2 on 2022-03-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_userlogin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curt',
            name='itmes',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
