# Generated by Django 4.0.2 on 2022-03-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_curt_itmes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
