# Generated by Django 4.0.2 on 2022-03-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_curt_itmes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curt',
            name='itmes',
            field=models.ImageField(blank=True, null=True, upload_to='product/items'),
        ),
    ]
