# Generated by Django 4.0.2 on 2022-03-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_title_amount'),
        ('app1', '0016_alter_curt_itmes'),
    ]

    operations = [
    ]
